spring.application.name=server

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/skillloop_db
spring.datasource.username=skillloop_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Server Port
server.port=9090
