spring.application.name=server

# Database Configuration (We will set up Postgres later)
# spring.datasource.url=jdbc:postgresql://localhost:5432/skillloop
# spring.datasource.username=postgres
# spring.datasource.password=password
# spring.jpa.hibernate.ddl-auto=update

# Server Port
server.port=8080
